apiVersion: operator.ibm.com/v1
kind: ManagementIngress
metadata:
  name: default
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
spec:
  managementState: "managed"
  imageRegistry: quay.io/opencloudio
  image:
    repository: "icp-management-ingress"
    tag: 2.5.1
  routeHost: ""
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 256Mi
  allowedHostHeader: ""
  cert:
    issuer:
      name: "cs-ca-clusterissuer"
      kind: "ClusterIssuer"
  config:
    disable-access-log: "true"
