apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-management-ingress-operator
  labels:
    app.kubernetes.io/name: ibm-management-ingress-operator
    app.kubernetes.io/instance: ibm-management-ingress-operator
    app.kubernetes.io/managed-by: ibm-management-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-management-ingress-operator
  template:
    metadata:
      labels:
        name: ibm-management-ingress-operator
        app.kubernetes.io/managed-by: "ibm-management-ingress-operator"
        app.kubernetes.io/name: "ibm-management-ingress-operator"
        app.kubernetes.io/instance: ibm-management-ingress-operator
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-management-ingress-operator
      containers:
        - name: ibm-management-ingress-operator
          image: quay.io/opencloudio/ibm-management-ingress-operator:latest
          command:
          - ibm-management-ingress-operator
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "./health_check.sh"]
            initialDelaySeconds: 5
            periodSeconds: 1
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "./health_check.sh"]
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-management-ingress-operator"
            - name: OPERAND_IMAGE_DIGEST
              value: "quay.io/opencloudio/icp-management-ingress:@sha256:c7f4960f2df024cd3b43b08d115047293359478b5b91b15e9f3b8c40a3af74d3"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ROUTE_HTTPS_PORT
              value: ""
            - name: ROUTE_HTTP_PORT
              value: ""
            - name: CLUSTER_NAME
              value: ""
            - name: VERSION
              value: ""
